#!/bin/sh
echo 'access by date:'
cut -f8 -d';' searchlog.txt | cut -c1-7 | uniq -c | perl -ne '/(\d+)\s(\d+)/; printf "%7d %4d %s\n", $2, $1, "#" x ($1/14);'
echo
cut -f5 -d';' itemlog.txt | cut -c1-7 | uniq -c | perl -ne '/(\d+)\s(\d+)/; printf "%7d %4d %s\n", $2, $1, "#" x ($1/14);'
echo
echo 'access by hour:'
cut -f8 -d';' searchlog.txt | cut -c8-9 | sort | uniq -c | perl -ne '/(\d+)\s(\d+)/; printf "%02d %4d %s\n", $2, $1, "#" x ($1/10);'
echo
cut -f5 -d';' itemlog.txt | cut -c8-9 | sort | uniq -c | perl -ne '/(\d+)\s(\d+)/; printf "%02d %4d %s\n", $2, $1, "#" x ($1/10);'
