#!/bin/sh
size=$1

LIST="aksess diverse ip kjop konsulent kurs media naeringsliv oslonett reiseliv sport underh www org"

echo -n "Headere i $1 format ..."
for fil in $LIST
do
  rm $fil-h.gif
  ln -s $1-$fil-h.gif $fil-h.gif
done

echo "done"
  
 