#!/bin/sh -x
PATH=/local/bin:/usr/ucb:/usr/bin:/bin
export PATH
cd /home/frogner/www/me/ts/aftenpo/rubrikk
KL=`date +%H`
if test -f rubrikk
then
   mv rubrikk rubdata
   pep -ob rubdata
   ./annonser.pl rubdata
   ./setnum.pl
elif test $KL -gt 12 
then 	test -f .error || Mail -s 'Feil i rubdata' www@a.sn.no  < feil.mail
	touch .error
fi

