#!/local/bin/perl

print "Content type: text/html\n\n";

$mal = '/local/www/ft/www/klipp-mal.html';

%gruppe = ('SPO', 'Sport',
	   'UTE', 'Utenriks',
	   'INN', 'Innenriks',
	   'RTV', 'Radio/TV',
	   'VLG', 'Valgstoff',
	   );
%input = &getinput;

open(MAL, $mal) || &error("Kunne ikke åpne maldokumentet $mal");

$heleord = "&heleord=ja"
    if ( $input{'heleord'} && $input{'heleord'} !~ /^nei$/i);

while ( ($key, $val) = each %input ) {
    next unless $key =~ s/^gr-(.+)/$1/;
    if ($key =~ s/-min$//) {
	$tid{$key} = $val;
    } else {
	$path = $key;
	$key =~ s%^([^/]+).+%$1%;
	$gr{$key} = $path;
    }
}

foreach (keys %gr) {
    $tid{$_} = 10 unless $tid{$_};
    $gruppenavn = $gruppe{$_} || $_;
    $gruppeliste .= qq! <li> <a href="/cgi-bin/NTBpull/$gr{$_}?$tid{$_}">$gruppenavn</a>\n!;
}

($urlsubtekst = $input{'subtekst'})
    =~ s/([\s&+%?])/sprintf("%%%02X", unpack("c",$1))/ge;
while (<MAL>) {
    s/<NAVN>/$input{'navn'}/g;
    s/<GRUPPER>/$gruppeliste/;
    s/<SUBTEKST>/$input{'subtekst'}/g;
    s/<URLSUBTEKST>/$urlsubtekst/g;
    s/<HELEORD>/$input{'heleord'}/g;
    print;
}
close(MAL);
exit 0;


sub getinput {
# Leser inn data (med method GET eller POST) og plasserer dem i en
# assosiativ array, der nøklene i array'en er feltnavnene

    local($i, $name, $value, $data, @data, %input);

    if ($ENV{'REQUEST_METHOD'} eq "GET") {
        $data = $ENV{'QUERY_STRING'};
    } elsif ($ENV{'REQUEST_METHOD'} eq "POST") {
        read(STDIN, $data, $ENV{'CONTENT_LENGTH'});
    } else {
        return undef;
    }

    # Del opp input-data i felter ved alle forekomster av '&'.
    @data = split(/&/, $data);

    for $i (0 .. $#data) {

        # Pluss oversettes til SPC
        $data[$i] =~ tr/+/ /;

        # Alt til venstre for første "=" er feltnavn, resten er felt-verdi
        ($name, $value) = split(/=/, $data[$i], 2);

        # Erstatt forekomster av %<hexkode> med tilsvarende tegn
        $name =~ s/%(..)/pack("c",hex($1))/ge;
        $value =~ s/%(..)/pack("c",hex($1))/ge;

        # Hvis kun whitespace er sendt med ignoreres dette name-value paret
        next if $value !~ /\S/;

        $input{$name} = $value;
    }
    %input;                     # returnerer den assosiative array'en
}
