#!/local/bin/perl

print "Content-type: text/html\n\n";

$top = '/local/www/ft/www/idag';

$filename = "$top/$ENV{'PATH_INFO'}/index.html";

open(FILE, $filename) || &error("Kunne ikke lese indeks-filen $filename");

$delay = $ENV{'QUERY_STRING'} * 60;
while (<FILE>) {
    s!<meta .+>!!i;
    s!</title>!</title>\n <META HTTP-EQUIV="Refresh" CONTENT="$delay">!i;
    print;
}

exit 0;

sub error {
    local($msg) = $_[0];

    print "<html>\n<head>\n<title>Feilmelding</title>\n</head>\n";
    print "<body>\n<h1>Feilmelding</h1>\n\n";
    print "Programmet ble avbrutt med følgende feilmelding:\n";
    print "<blockquote>\n<hr><b>$msg</b><hr>\n</blockquote>\n";
    print "</body>\n</html>\n";

    exit 0;
}

