#!/local/bin/perl

# addtb filnavn1 filnavn2 ...
#
# Programmet legger på topp- og bunn-tekst for alle input-filene (med mindre
# <head>-tag allerede finnes i dokumentet). Programmet spør etter ønsket
# dokument-tittel (med default = <h1>).

$EXT = ".bak";
$HTMLDIR = "http://www.oslonett.no/html/adv/BNbank";
$GIFDIR = "http://www.oslonett.no/html/adv/BNbank/gifs";

file: foreach $name (@ARGV) {
    print STDERR "Behandler $name, ";
    if (!rename($name, $name.$EXT)) { warn $!; next; }
    if (!open(IN, $name.$EXT)) { warn $!; next file; }
    if (!open(OUT, ">$name")) { warn $!; next file; }

    @all = <IN>;

    line: foreach ( @all ) {
	if ( /<head>/i ) {
	    warn "filen har allerede <head>-tag. Ikke endret.\n";
	    rename($name.$EXT, $name);
	    next file;
	}
	($h1) = m#<h1>([^<]+)</h1>#;
	last line if $h1;
    }

    print STDERR "oppgi dokument-tittel ($h1): ";
    $title = <STDIN>;
    chop($title);
    $title = $h1 unless $title;

    print OUT <<EOT;
<html>
<head>
    <title>$title</title>
</head>
<body background="$GIFDIR/bnmnste.gif" text="#000000">
<center>
    <a href="$HTMLDIR/innskudd.html>
        <img alt="Innskudd" src="$GIFDIR/BNinnskudd.gif" border=0></a>
    <a href="$HTMLDIR/boliglaan.html>
        <img alt="Boliglån" src="$GIFDIR/BNboliglaan.gif" border=0></a>
    <a href="$HTMLDIR/pantelaan.html>
        <img alt="Næringslån" src="$GIFDIR/BNnaeringslaan.gif" border=0></a>
    <a href="$HTMLDIR/info.html>
        <img alt="Informasjon" src="$GIFDIR/BNinformasjon.gif" border=0></a>
    <a href="$HTMLDIR/bnforvaltning.html>
        <img alt="Font" src="$GIFDIR/BNfond.gif" border=0></a>
    <p>
    <img alt="BNbank" src="$GIFDIR/header-logo.gif">
</center>
<p>
@all
<p>
<center>
<h2><em>Bedre betingelser på innskudd og utlån</em></h2>
</center>
<hr noshade size=1>
<a href="/index.html">
    <img alt="[Oslonett Home]" src="/graphics/home.gif"></a>
<a href="/html/adv/ON-market.html">
    <img alt="[Oslonett Markedsplassen]" src="/graphics/market.gif"></a>
<a href="$HTMLDIR/index.html">
    <img alt="[BNbanks hjemmeside]" src="$GIFDIR/footer-logo.gif"></a>
</body>
</html>
EOT

    close(OUT);
    close(IN);
}

exit 0;
