#!/local/bin/perl -w
#
# Usage:	splitt <inputfil> <utgavenr>
# 		splitt GOAL_tekst2.txt 9502
#
# Programmet skriver hver artikkel til hver sin fil: goalYYUUNN.html
# (YY=år, UU=utgave, NN=nr. YYNN er gitt ved argument to i kallet over)
# Programmet lager også filen goalYYNNindex.html
#
# Følgende antas om input-filene:
#  - mac-tegnsett
#  - artikkel avsluttes med to eller flere blanke linjer
#  - <h1> er første linje i artikkelen, evt. flere ikke-blanke linjer
#    før første blanke kodes som hver sin <h2>
#  - Hver linje i input-filen er ett avsnitt.
#  - Hvis første linje i et avsnitt er kortere enn 40 tegn tolkes dette
#    som en avsnittsoverskrift og den tag'es med <h2>


$MAKSLENGDE = 50;
$INNHOLD = qq!<a href="index.html">[Innholdsfortegnelse]</a>!;
$FORSIDE = qq!<a href="/me/ts/goal/">[GOALs forside]</a>!;
$NESTETAG = "<!-- neste: -->";
$bodyattributt = qq! bgcolor="#503060" text="#ffffff" link="#ffffaa" vlink="#ffffaa"!;

#open(STDERR, ">/dev/null");	# Orker ikke høre støyen fra "pep"

die qq!Usage: $0 <inputfil> <utgavenr på formatet 9503> [<body>-attributt]\n(Default body-attributt er 'bgcolor="#503060" text="#ffffff" link="#ffffaa" vlink="#ffffaa"')\n!
    if scalar(@ARGV) < 2 || $ARGV[1] !~ /^\d{4}$/;

die "Kunne ikke åpne input-filen $ARGV[0]\n" unless -r $ARGV[0];

$bodyattributt = " " . join(" ", @ARGV[2,$#ARGV]) if length $ARGV[2];

# pep© er fint til å vaske bort mac-tegn, kaster støyende glad-meldinger

open(ALL, "/local/bin/pep -gmac2iso $ARGV[0] 2> /dev/null |")
    || die "Kunne ikke kjører 'pep'\n";

open(INDEX, ">goal$ARGV[1]index.html")
    || die "Kunne ikke åpne indeks-filen goal$ARGV[1]index.html\n";

($nr, $aar) = ($2, $1) if $ARGV[1] =~ /(\d\d)(\d\d)/;
print INDEX &header("Innholdsfortegnelse for GOAL nr. $nr 19$aar");
print INDEX "<ul>\n";
$artikkelnr=0;
open(ART, ">/dev/null");	# dummy open forenkler "nyartikkel"
&nyartikkel;

while (<ALL>) {
    chop;

    # blank linje ==> nytt avsnitt

    if ( /\S/ ) {
	$blankelinjer = 0;
    } else {
	$blankelinjer++;
    }

    &nyartikkel if $blankelinjer >= 2;

    if ( $blankelinjer ) {
	$nyttavsnitt = 1;
	print ART "\n";
	next;
    }

    if ($nyttavsnitt && length $_ < $MAKSLENGDE) {
	print ART "<h2>$_</h2>\n";
	next;
    }

    $nyttavsnitt = 0;

    #bryt opp lange linjer
    s/(.{50,70})\s+/$1\n/g;

    print ART "$_<p>\n\n";
}

print ART &footer($artikkelnr);
close ART;

print INDEX "</ul>\n";
close INDEX;

# siste fil har en ulovlig neste-peker. Den må fjernes:
system("/local/bin/perl -i -pe 's/^$NESTETAG.+//;' $filnavn");

print "Har laget $artikkelnr artikler med navn 'goal$ARGV[1]nn.html' samt\n";
print "innholdsfortegnelse med navn 'goal$ARGV[1]index.html\n";
exit 0;


sub nyartikkel {
    print ART &footer($artikkelnr);
    close ART;

    $h1seen = 0;

    $filnavn = sprintf("goal%s%02d.html", $ARGV[1], ++$artikkelnr);

    open(ART, ">$filnavn")
	|| exit "Kunne ikke skrive filen $filnavn - konvertering avbrutt!\n";
    while (<ALL>) {
	chop;
	next if !$h1seen && !/\S/;
	unless ($h1seen++) {
	    print INDEX qq! <li> <a href="$filnavn">$_</a>\n!;
	    print ART &header($_);
	    next;
	}
	last unless /\S/;
	last if length $_ > $MAKSLENGDE;
	print ART "<h2>$_</h2>\n";
    }
}


sub header {
    local($title) = $_[0];

    return <<EOT;
<html>
<head>
 <title>GOAL: $title</title>
</head>
<body$bodyattributt>

<center>
<hr>
  <a href="/me/ts/goal/"><img alt="" src="/me/ts/goal/gifs/goal_200.gif" width="150" border=0></a>
<hr>
<h1>$title</h1>
</center>
EOT
}


sub footer {
    local($i) = $_[0];

    $forrige	= "";
    $forrige	= sprintf(qq!<a href="goal$ARGV[1]%02d.html">[Forrige]</a>!
			  , $i-1) if $i > 1;

    $neste	= sprintf(qq!<a href="goal$ARGV[1]%02d.html">[Neste]</a>!
			  , $i+1);

# NB! Kommentaren $NESTETAG må være med for å kunne slette nestepeker i 
# siste artikkel.

    return <<EOT;
<hr>
<center>
$forrige
$INNHOLD
$FORSIDE
$NESTETAG $neste
</center>
</body>
</html>
EOT
}
