#!/local/bin/perl -- -*-perl-*-

# ------------------------------------------------------------

# Form-mail.pl, by Reuven M. Lerner (reuven@the-tech.mit.edu).
# This is a rewrite of a program that was trashed by our power
# surge in the middle of February 1994.

# ------------------------------------------------------------

# Bugs and other fixes

# March 1, 1994 (Reuven)
# Fixed security hole that could result from people
# executing subshells
# ------------------------------------------------------------

# Define fairly-constants
$mailprog = "/usr/ucb/mail -s \"Elektronisk bestilling av CD'er fra Akers Mic!\"";
$recipient = "arneom@oslonett.no";

# Get the input
read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});

# Split the name-value pairs
@pairs = split(/&/, $buffer);

foreach $pair (@pairs)
{
    ($name, $value) = split(/=/, $pair);
    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;

    # Stop people from using subshells to execute commands
    $value =~ s/~!/ ~!/g; 

    # Uncomment for debugging purposes
    # print "Setting $name to $value<P>";

    $FORM{$name} = $value;
}

# Print out what we need
print "Set-Cookie: navn=$FORM{'navn'};adresse=$FORM{'adresse'};postnr=$FORM{'postnr'};poststed=$FORM{'poststed'};email=$FORM{'email'};visakortnummer=$FORM{'visakortnummer'};path=\;expires=Wednesday, 09-Nov-99 23:23:23 GMT \n";
print "Content-type: text/html\n\n";
print "<Head><Title>Kvittering</Title></Head>";
print "<Body BACKGROUND=\"http://www.oslonett.no/home/akersm/gifs/bg2.gif\" rgb=\"#ff00ff\" TEXT=\"#FFFF00\" LINK=\"#00FF7F\" VLINK=\"#38B0DE\" ALINK=\"#0077FF\">\n";
print "<center><IMG SRC=http://www.oslonett.no/home/akersm/gifs/topp20.gif></center>\n";
print "<center><H1>Kvittering</H1></center>\n";
print "Følgende CD-bestilling ble sendt til Akers Mic:\n";

# Now send mail to $recipient

open (MAIL, "|$mailprog $recipient") || die "Can't open $mailprog!\n";
print MAIL "Hei!\n\n";
print MAIL "Nedenfor er det en elektronisk bestilling av CD'er:\n";
print MAIL "      Navn: $FORM{'navn'}\n";
print MAIL "   Adresse: $FORM{'adresse'}\n";
print MAIL "  Postnr: $FORM{'postnr'} $FORM{'poststed'}\n";
print MAIL "     Email: $FORM{'email'}\n";
print MAIL "Visakortnr: $FORM{'visakortnummer'}\n\n";
print MAIL "Følgende CD'er ble bestilt:\n";
print MAIL "CD no 1: $FORM{'cd1'}\n";
print MAIL "CD no 2: $FORM{'cd2'}\n";
print MAIL "CD no 3: $FORM{'cd3'}\n";
print MAIL "CD no 4: $FORM{'cd4'}\n";
print MAIL "CD no 5: $FORM{'cd5'}\n";
print MAIL "CD no 6: $FORM{'cd6'}\n";
print MAIL "CD no 7: $FORM{'cd7'}\n";
print MAIL "CD no 8: $FORM{'cd8'}\n";
print MAIL "CD no 9: $FORM{'cd9'}\n";
print MAIL "CD no 10: $FORM{'cd10'}\n";
print MAIL "CD no 11: $FORM{'cd11'}\n";
print MAIL "CD no 12: $FORM{'cd12'}\n";
print MAIL "CD no 13: $FORM{'cd13'}\n";
print MAIL "CD no 14: $FORM{'cd14'}\n";
print MAIL "CD no 15: $FORM{'cd15'}\n";
print MAIL "CD no 16: $FORM{'cd16'}\n";
print MAIL "CD no 17: $FORM{'cd17'}\n";
print MAIL "CD no 18: $FORM{'cd18'}\n";
print MAIL "CD no 19: $FORM{'cd19'}\n";
print MAIL "CD no 20: $FORM{'cd20'}\n";
  
print MAIL "Remote host: $ENV{'REMOTE_HOST'}\n";
print MAIL "Remote IP address: $ENV{'REMOTE_ADDR'}\n";
close (MAIL);

print "<pre>\n";
print  "      Navn: $FORM{'navn'}\n";
print  "   Adresse: $FORM{'adresse'}\n";
print  "  Poststed: $FORM{'postnr'} $FORM{'poststed'}\n";
print  "     Email: $FORM{'email'}\n";
print  "Visakortnr: $FORM{'visakortnummer'}\n\n";
print "</pre>\n";
print  "Følgende CD'er ble bestilt:\n<ul>\n";
print  "<li> CD no 1: $FORM{'cd1'}\n";
print  "<li> CD no 2: $FORM{'cd2'}\n";
print  "<li> CD no 3: $FORM{'cd3'}\n";
print  "<li> CD no 4: $FORM{'cd4'}\n";
print  "<li> CD no 5: $FORM{'cd5'}\n";
print  "<li> CD no 6: $FORM{'cd6'}\n";
print  "<li> CD no 7: $FORM{'cd7'}\n";
print  "<li> CD no 8: $FORM{'cd8'}\n";
print  "<li> CD no 9: $FORM{'cd9'}\n";
print  "<li> CD no 10: $FORM{'cd10'}\n";
print  "<li> CD no 11: $FORM{'cd11'}\n";
print  "<li> CD no 12: $FORM{'cd12'}\n";
print  "<li> CD no 13: $FORM{'cd13'}\n";
print  "<li> CD no 14: $FORM{'cd14'}\n";
print  "<li> CD no 15: $FORM{'cd15'}\n";
print  "<li> CD no 16: $FORM{'cd16'}\n";
print  "<li> CD no 17: $FORM{'cd17'}\n";
print  "<li> CD no 18: $FORM{'cd18'}\n";
print  "<li> CD no 19: $FORM{'cd19'}\n";
print  "<li> CD no 20: $FORM{'cd20'}\n</ul>\n<p>\n";
print "</body>\n</html>\n";
  

