#!/local/bin/perl -- -*-perl-*-


# Get the input
read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});

# Split the name-value pairs
@pairs = split(/&/, $buffer);

foreach $pair (@pairs)
{
    ($name, $value) = split(/=/, $pair);
    $value =~ tr/+/ /;
    $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;

    # Stop people from using subshells to execute commands
    $value =~ s/~!/ ~!/g; 

    # Uncomment for debugging purposes
    # print "Setting $name to $value<P>";

    $FORM{$name} = $value;
}

print "Content-type: text/html\n\n";
print "<Head><Title>Bestilling av CD'er fra Akers Mic</Title></Head>";
print "<Body BACKGROUND=\"http://www.oslonett.no/home/akersm/gifs/bg2.gif\" rgb=\"#ff00ff\" TEXT=\"#FFFF00\" LINK=\"#00FF7F\" VLINK=\"#38B0DE\" ALINK=\"#0077FF\">\n";
print "<center><IMG SRC=http://www.oslonett.no/home/akersm/gifs/topp20.gif></center>\n";
print "<center><H1>Bestilling av CD'er fra Akers Mic</H1></center>";
print "Du er nå inne i selve bestillingsskjemaet. Tast inn navn, adresse, emailadresse og Visakortnummer, så vil du få CD'ene tilsendt i posten.<p>\n\n";

print "<FORM method=\"POST\"  ACTION=\"http://www.oslonett.no/cgi-bin/bestillCD/\" >\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd1\" VALUE=\"$FORM{'cd1'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd2\" VALUE=\"$FORM{'cd2'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd3\" VALUE=\"$FORM{'cd3'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd4\" VALUE=\"$FORM{'cd4'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd5\" VALUE=\"$FORM{'cd5'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd6\" VALUE=\"$FORM{'cd6'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd7\" VALUE=\"$FORM{'cd7'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd8\" VALUE=\"$FORM{'cd8'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd9\" VALUE=\"$FORM{'cd9'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd10\" VALUE=\"$FORM{'cd10'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd11\" VALUE=\"$FORM{'cd11'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd12\" VALUE=\"$FORM{'cd12'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd13\" VALUE=\"$FORM{'cd13'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd14\" VALUE=\"$FORM{'cd14'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd15\" VALUE=\"$FORM{'cd15'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd16\" VALUE=\"$FORM{'cd16'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd17\" VALUE=\"$FORM{'cd17'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd18\" VALUE=\"$FORM{'cd18'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd19\" VALUE=\"$FORM{'cd19'}\">\n";
print "<INPUT TYPE=\"hidden\" NAME=\"cd20\" VALUE=\"$FORM{'cd20'}\">\n";

print "<pre>\n";
print "Kundenavn     : <INPUT TYPE=text NAME=navn MAXLENGTH=65 SIZE=65>\n";
print "Adresse       : <INPUT TYPE=TEXT NAME=adresse MAXLENGTH=65 SIZE=65>\n";
print "Postnummer    : <INPUT TYPE=TEXT NAME=postnummer MAXLENGTH=5 SIZE=5> Poststed : <INPUT TYPE=text NAME=poststed MAXLENGTH=30 SIZE=30>\n";

print "Email         : <INPUT TYPE=TEXT NAME=email MAXLENGTH=50 SIZE=50>\n";
print "Visakortnummer: <INPUT TYPE=TEXT NAME=visakortnummer MAXLENGTH=50 SIZE=50>\n"; 
print "</pre>\n";
print "<center>\n<input type=submit value=\"Send bestilling\">\n<input type=reset value=\"Reset bestillingsskjemaet\">\n</center>\n";

print  "<p>Remote host: $ENV{'REMOTE_HOST'}<p>\n";
print  "Remote IP address: $ENV{'REMOTE_ADDR'}<p>\n";

print "</body>\n";
print "</html>\n"
