#!/bin/sh

## Dette skriptet bytter ut xxxx i filene med $1 og yyyy med $2

PATH=/bin:/local/bin:/usr/bin:/usr/ucb

#echo "Content-type: text/html"
#echo 
sed -e "s/xxxx/$1/g"  -e "s/yyyy/$2/g" $3

exit 0;

