#!/local/bin/perl -w

$W = 70;
$H = 100;

%scheme = 
(
 std => { 
     font  => "Times-Roman",
     scale => 0.2,
     bg    => 0,
     bd    => 0.7,
     fg    => 1,
 },
 big => {
     font  => "URWAntiquaT-RegularCondensed",
     scale => 0.4,
     bg    => 0,
     bd    => 0,
     fg    => 1,
     w     => 50,
 },
 grotesk => {
     font  => "URWGroteskT-Bold",
     scale => 0.2,
     bg    => 1,
     bd    => 0.9,
     fg    => 0,
 },
);

$scheme = shift || "std";
die "Unknown scheme\n" unless exists $scheme{$scheme};

$NAME  = $scheme;
$FONT  = $scheme{$scheme}{font};
$SCALE = $scheme{$scheme}{scale};
$FG    = $scheme{$scheme}{fg};
$BD    = $scheme{$scheme}{bd};
$BG    = $scheme{$scheme}{bg};
$W     = $scheme{$scheme}{w} || $W;

%filename = (
 ' ' => 'space',
 ',' => 'comma',
 '.' => 'period',
 '+' => 'plus',
 '-' => 'minus',
);

for (0 .. 9) {
    $filename{$_} = $_;
}


for (0 .. 9, ' ', ',', '.', '+', '-') {
   $file = $filename{$_};
   next unless defined $file;
   $file = "$NAME-$file";
   local($W) = $W/2 if $_ eq '.' || $_ eq ',';


   $cmd = "gs -q -sDEVICE=ppm -g${W}x${H} '-sOutputFile=$file.ppm~' -";
   print "$cmd\n";

   open(GS, "| $cmd");
   print GS <<"EOT";
%!PS-Adobe-3.0

/SF/setfont load def
/NE {
   findfont begin
      currentdict dup length dict begin
         { %forall
            1 index/FID ne {def} {pop pop} ifelse
         } forall
         /FontName exch def
         /Encoding exch def
         currentdict dup
      end
   end
   /FontName get exch definefont pop
} bind def
%%EndResource

$BG setgray clippath fill

$BD setgray
4 setlinewidth 
clippath stroke

$FG setgray


ISOLatin1Encoding /$FONT-ISO/$FONT NE

/$FONT-ISO findfont 100 scalefont setfont
$W 2 div 15 moveto
($_) dup stringwidth pop 2 div neg 0 rmoveto show
showpage
EOT

   close(GS);

   run("pnmscale $SCALE '$file.ppm~' >'$file.ppm'");
   unlink("$file.ppm~");
   push(@files, "$file.ppm");
}

#run("ppmquantall 16 @files");
for $ppm (@files) {
    ($pgm = $ppm) =~ s/\.ppm$/.pgm/;
    run("ppmtopgm '$ppm' >'$pgm'");
    unlink($ppm);
}

sub run
{
    print "@_\n";
    system @_;
}
