#!/bin/sh
#
# update - oppdaterer b|rsinformasjonen. kalles (typisk) av cron.
#
# skrevet av Ketil Kirkerud, SN, 11. desember 1995
#

siste=`ls -t /home/frogner/www/nl/fi/boers/log/*.log | head -1`
cd /home/frogner/www/nl/fi/boers/log
rm -f sistelog
ln $siste sistelog
cd /home/frogner/www/nl/fi/boers2
/home/frogner/www/nl/fi/boers2/decode.pl < $siste

